--- 
Duration (s): 120
Sensors: 
  - 
    Interval (ms): 1000
    Name: "bl 1"
    Sensor: Blocking
  - 
    Interval (ms): 6000
    Name: "nb 1"
    Sensor: NonBlocking
  - 
    Interval (ms): 600
    Name: "bl 2"
    Sensor: Blocking
  - 
    Interval (ms): 5000
    Name: "nb 2"
    Sensor: Blocking
  - 
    Interval (ms): 7000
    Name: "nb 3"
    Sensor: NonBlocking
